#:schema ../../api/generated/font.json
id        = "sitelen pona Elopa pi ma Sapu"
name      = "sitelen pona Elopa pi ma Sapu"
filename  = "sitelen-pona-Elopa-pi-ma-Sapu.ttf"
creator   = ["jan Ke Tami + jan Pate + jan Ukamika + jan Jonatan Lise + jan Mikali + jan Simo + jan Nikilase + jan Kasape + jan Tekinowi + jan Sewa + jan Tepo + kon Temasuke + jan Piku + jan Ani + sike Sapi + jan Tamalu + jan Lna + jan Sapina + jan Osin + jan Mateja + jan Simiman + jan Okan + jan Olipija + ijo vivi + jan Emilo + jan Lusi + jan Pako + loje Kija + jan Lin + jan Alonola + jan Sonatan + jan Melisuwi + jan Molisi + jan Leki + jan Lisaki + jan Mila + jan Neli + jan Sowan + kasi Linwe + jan Mate + jan Lewe + jan Masine + jan Lim"]
license   = "CC0-1.0"
ligatures = true
ucsur     = true
writing_system = "sitelen pona"

last_updated = "2025-08"
version      = "1"

features = [
  "ASCII transcription and codepoints",
  "UCSUR-compliant",
  "cartouches",
  "SP Font Maker words v2.2",        # unless they didn't fill out all the words

  # "incomplete",
  # "variable weight",
  # "name glyphs",
  # "character variants",
  # "Linku common & uncommon 2024"   # nimisin
  # "all ku suli",                   # kokosila
  # "all ku suli and UCSUR words",   # apeja, pake, powe
  # "community requested nimisin",

  # Not implemented in SP Font Maker:
  # "long pi",
  # "randomized jaki",
  # "ZWJ sequences",
  # "tuki tiki",
]

# Pick one style, or put multiple comma-separated styles in quotes.
style = "handwritten"
# style = "alternate design"
# style = "uniform line weight"
# style = "pixelated"
# style = "handdrawn"
# style = "serif"
# style = "sans-serif"
# style = "faux 3d"
# style = "unspecified"

[links]
# Autofilled for Kelly. If you're not Kelly, these URLs are inaccurate; upload the font to a website like neocities.org or github.io
fontfile = "https://github.com/wasokeli/wasokeli.github.io/raw/main/sp-font-maker/sitelen-pona-Elopa-pi-ma-Sapu.ttf"
repo     = "https://github.com/wasokeli/wasokeli.github.io/tree/main/sp-font-maker"
webpage  = "https://wasokeli.github.io/sp-font-maker/sitelen-pona-Elopa-pi-ma-Sapu.html"

