#:schema ../../api/generated/font.json
id        = "sitelen leko Teto"
name      = "sitelen leko Teto"
filename  = "sitelen-leko-Teto.ttf"
creator   = ["jan tonsi Puki"]
license   = "OFL-1.1"
ligatures = true
ucsur     = true
writing_system = "sitelen pona"

last_updated = "2025-08"
version      = "1.0"

features = [
  "UCSUR-compliant",
  "ASCII transcription",
  "words containing capitalized or impossible characters are ignored for transcription",
  "extended pi",
  "cartouches",
  "capitalized words in cartouches are transcribed to sitelen pona glyphs",
  "cartouches inside extended pi",
  "tally marks in cartouches"
]

style = "pixelated"

[links]
fontfile = "https://git.hemio.de/example/sitelen_leko_Teto/-/raw/main/versions/1.0/sitelen_leko_Teto.ttf"
repo     = "https://git.hemio.de/example/sitelen_leko_Teto"
