#:schema ../../../api/generated/sign.json
definition = "lili"
id = "LILI"
is_two_handed = false
new_gloss = "LILI-SUPA"
old_gloss = "LILI"

[[etymology]]
language = "multiple SLs"
sign = "CHILD, SHORT"

[signwriting]
fsw = "AS15a50S22b04M508x532S15a50494x468S22b04492x502"
swu = "𝠀񂈑񇀥𝠃𝤎𝤦񂈑𝤀𝣦񇀥𝣾𝤈"

[video]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/lili.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/lili.mp4"
