#:schema ../../../api/generated/sign.json
definition = "linja"
id = "LINJA"
is_two_handed = false
new_gloss = "LINJA-1"
old_gloss = "LINJA"

[[etymology]]
language = "Toki Pona Sign Language (Chuff)"
sign = "linja"

[signwriting]
fsw = "AS1ce20S22b06M528x515S1ce20472x485S22b06498x499"
swu = "𝠀񄵡񇀧𝠃𝤢𝤕񄵡𝣪𝣷񇀧𝤄𝤅"

[video]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/linja.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/linja.mp4"
