#:schema ../../../api/generated/sign.json
definition = "pali"
id = "PALI^1"
is_two_handed = false
new_gloss = "PALI-LUKA"
old_gloss = "PALI"

[[etymology]]
language = "multiple SLs"
sign = "WORK, MAKE"

[signwriting]
fsw = "M515x519S15a37485x481S1f550491x488S20600491x508"
swu = "𝠃𝤕𝤙񂇸𝣷𝣳񅰱𝣽𝣺񆉁𝣽𝤎"

[video]
gif = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/gif/pali.gif"
mp4 = "https://raw.githubusercontent.com/lipu-linku/ijo/main/lukapona/mp4/pali.mp4"
